### ISSUE TITLE
User Manual

### ISSUE THREAD

**Issue by Saman-Khan** [bhuman/SimRobot#1]
Is there some detailed documentation available to use SIMROBOT for BHuman Code release? Or some tutorials on how to check different code modules in simulation environment. The code release documentation is confusing. Also, is there any active community where we can get help quickly.  
Another thing, do I need to calibrate joints and camera before running simulation or is it only for hardware robot. A quick reply is appreciated

**Comment by antbono** [comment]
as a beginner, I am also finding it difficult to use the simulator. A detailed guide or tutorial on how to start testing various modules would be greatly appreciated. Thank you!

**Comment by Saman-Khan** [comment]
> as a beginner, I am also finding it difficult to use the simulator. A detailed guide or tutorial on how to start testing various modules would be greatly appreciated. Thank you!

Hi, please let me know if u found any help on testing various modules. I tried contacting people from the team but I haven't been successful yet

**Comment by ahasselbring** [comment]
bhuman/BHumanCodeRelease#47

(Also, you are probably not looking for documentation about SimRobot, but about B-Human's SimRobot controller.)
