### ISSUE TITLE
Moving Objects in SimRobot

### ISSUE THREAD

**Issue by Saman-Khan** [bhuman/SimRobot#2]
I have a scene containing a ball. I wanted to apply some force so that the ball rolls in a direction according to specified speed based on applied force. The translation defined as part of scene configuration file translates the object in beginning when scene is loaded. I need guidance to move objects in simulator from one place to another after some specified time. Pl guide where I can find the documentation

**Comment by ahasselbring** [comment]
SimRobotCore2 currently does not provide an API to apply forces or set velocities to objects (though it would be possible to add those functions as they are used internally in the drag and drop modes of the SimObjectRenderer).

To move objects without changing their dynamic properties, the [methods](https://github.com/bhuman/SimRobot/blob/c4b27490f9f2a23332b1c8d7d7668a4b18867c67/Src/SimRobotCore2/SimRobotCore2.h#L319) of `SimRobotCore2::Body` can be used if you have a pointer to the object.

**Comment by Saman-Khan** [comment]
Hi, actually the aim was to visualize a rolling object in simulator. I tried the method u suggested, It works, but as it changes the absolute position of object in every update cycle of controller, the movement is really fast and not realistic. Any guidance on how to simulate a rolling ball movement in environment that is close to realistic one. 
Also , any help on how the same can be incorporated inside B-Human Soccer simulation code ( one idea is to make one striker kick the ball and then the ball will roll as per ODE but with that , but then to adjust the speed of rolling ball , i would be needing different sort of kicks ) . The objective was to visualize dynamic objects in soccer simulation environment. The changes I made are shown below
![Capture](https://user-images.githubusercontent.com/15613013/184512003-d2991d0d-12e8-47f9-b234-9a221420c9de.PNG)

**Comment by ahasselbring** [comment]
If you want this functionality you have to implement it yourself. It involves adding a pure virtual function to the `Body` interface in `SimRobotCore2.h` and implementing that function in the `Body` class in `Simulation/Body.{cpp, h}`. The ODE call would be something like `dBodySetLinearVel(body, v[0], v[1], v[2]);` or `dBodyAddForce(body, f[0], f[1], f[2]);` depending on whether you want to set the velocity or apply a force (I think a force is applied at the CoM).

**Comment by Saman-Khan** [comment]
It worked. Thanks a lot. You are amazing :D
