### ISSUE TITLE
Adding a texture from an image

### ISSUE THREAD

**Issue by PetriJF** [bhuman/SimRobot#3]
Hello!

I've been attempting to figure this out for the past day or so but I am not sure how the texture system works in SimRobot.
I created a scene and added a body (simply 0.5m cube). I attempted multiple common texture patterns but no matter what I try, it never works.

A few examples of what I tried:
- ![eee](https://github.com/bhuman/SimRobot/assets/39564368/c26dc481-db6c-48bb-853f-2c938bc05a1b)
- ![ccc](https://github.com/bhuman/SimRobot/assets/39564368/b9464e07-ab72-449a-9086-6e933d7fd39f)
- ![ddd](https://github.com/bhuman/SimRobot/assets/39564368/038db14b-f288-4cc0-9f3a-016aba78075d)

However nothing works and I simply can't figure out the logic behind it.
What is consistent is that the top and bottom sides of the cube get some sort of pattern on them, while the sides get an extended version of the pattern.
Here is an example (for the second pattern I gave):
![Screenshot from 2024-04-19 16-36-14](https://github.com/bhuman/SimRobot/assets/39564368/f727c1e6-0583-4f46-aabd-86468c8e94b9)

Do you have any documentation that goes deeper on the aspects behind adding custom objects and texturing them?

**Comment by ahasselbring** [comment]
It looks like you're using a BoxAppearance. That simply maps the x/y plane to u/v coordinates, so texturing is only really useful for flat objects like the field. Basically, for all other purposes, you should use a ComplexAppearance with a TexCoords subelement. This allows you to specify texture coordinates for each vertex.

```xml
<ComplexAppearance>
  <Vertices>
0 0 0  # x/y/z of vertex 0
0 0 1  # x/y/z of vertex 1
0 1 1  # x/y/z of vertex 2
  </Vertices>
  <TexCoords>
0 0  # u/v of vertex 0
0 1  # u/v of vertex 1
1 0  # u/v of vertex 2
  </TexCoords>
  <Triangles>
0 1 2
  </Triangles>
  <Surface .../>
</ComplexAppearance>
```

**Comment by PetriJF** [comment]
That makes sense!
Thank you!
